version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  Build: # This is our first job.
    docker: # it uses the docker executor
      - image: python:3.8.10-alpine3.13 # specifically, a docker image with ruby 2.4.1
#        auth:
#          username: mydockerhub-user
#          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - setup_remote_docker:
          version: 19.03.8
          docker_layer_caching: false
      - run:
          name:
          command: |
            docker build -t isaias:$CIRCLE_SHA1
      - run: echo "Build Executado com Sucesso" # a command telling the job to "sleep" for 25 seconds.
  Test: # This is our second job.
    docker: # it runs inside a docker image, the same as above.
      - image: ubuntu:20.04
#        auth:
#          username: mydockerhub-user
#          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: sleep 15 # and then sleep for 15 seconds.
# Under the workflows: map, we can coordinate our two jobs, defined above.
workflows:
  version: 2
  Build and Test: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - Build
      - Test