version: 2
jobs:
  Build:
    docker:
      - image: docker:19.03.15
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
          docker_layer_caching: false
      - run:
          name:
          command: |
            docker build -t isaias:$CIRCLE_SHA1 .
            docker login -u $DOCKER_USER -p $DOCKERHUB_PASSWORD
            docker tag isaias:$CIRCLE_SHA1 isaiasonthecloud/isaias:$CIRCLE_SHA1
            docker push isaiasonthecloud/isaias:$CIRCLE_SHA1
      - run: echo "Build Executado com Sucesso"
  Test:
    docker:
      - image: docker:19.03.15
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.8
          docker_layer_caching: false
      - run:
          name:
          command: |
            docker run -d --name my-app isaiasonthecloud/isaias:$CIRCLE_SHA1
            sleep 10
            docker exec my-app curl --retry 10 --retry-connrefused http://localhost:5000/healthy
      - run: echo "Test Executado com Sucesso"
workflows:
  version: 2
  Build and Test:
    jobs:
      - Build
      - Test:
          requires:
            - Build