version: 2
jobs: # we now have TWO jobs, so that a workflow can coordinate them!
  Build: # This is our first job.
    docker: # it uses the docker executor
      - image: docker:19.03.15 # specifically, a docker image with ruby 2.4.1
        auth:
          username: $DOCKER_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - setup_remote_docker:
          version: 19.03.8
          docker_layer_caching: false
      - run:
          name:
          command: |
            docker build -t isaias:$CIRCLE_SHA1 .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USER --password-stdin
            docker push isaias:$CIRCLE_SHA1
      - run: echo "Build Executado com Sucesso" # a command telling the job to "sleep" for 25 seconds.
  Test: # This is our second job.
    docker: # it uses the docker executor
      - image: docker:19.03.15 # specifically, a docker image with ruby 2.4.1

    # Steps are a list of commands to run inside the docker container above.
    steps:
      - checkout # this pulls code down from GitHub
      - setup_remote_docker:
          version: 19.03.8
          docker_layer_caching: false
      - run:
          name:
          command: |
            docker run -d --name my-app isaias:$CIRCLE_SHA1
            docker exec my-app curl --retry 10 --retry-connrefused http://localhost:5000/healthy
      - run: echo "Test Executado com Sucesso" # a command telling the job to "sleep" for 25 seconds.
workflows:
  version: 2
  Build and Test: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - Build
      - Test