name: ms-s3-interaction
on: [push]
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build-docker:
    runs-on: ubuntu-latest
    steps:
        name: Setup Docker Buildx
      - uses: docker/setup-buildx-action@v1
        name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: isaias/app:latest

