name: ms-s3-interaction
on: [push]
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build S3 Interaction Image
        id: docker_build
        run: docker build -t s3_interaction:${GITHUB_SHA::8} .

      -
        name: Show Docker Image
        run : docker images

