name: ms-s3-interaction
on: [push]
jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build S3 Interaction Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
           push: false
           tag_with_ref: true
      -
        name: Show Docker Image
        run : echo ${{ steps.docker_build.outputs.digest }}

